package constants

// SHARED ARCHETYPE CONSTANTS
const PROCESS_NAME = "PROCESS_NAME"

// ARCHETYPE SUBSCRIPTION CONTANTS
const SUBSCRIPTION_NAME = "SUBSCRIPTION_NAME"
const SUSBCRIPTION_SIGNAL_BROKEN = "SUSBCRIPTION_SIGNAL_BROKEN"
const RAW_EVENT = "RAW_EVENT"
const UNMARSHALED_EVENT = "UNMARSHALED_EVENT"
const ERROR_UNMARSHALING_EVENT = "ERROR_UNMARSHALING_EVENT"

// ARCHETYPE RESTY CONSTATS
const REQUEST_BODY = "REQUEST_BODY"
const RESPONSE_BODY = "RESPONSE_BODY"
const STATUS_CODE = "STATUS_CODE"
